package com.gmail.bobason01.cinematicmanager.manager;

public enum LangKey {
    // 시스템 공통
    PREFIX("prefix"),

    // 메뉴 관련
    MENU_MAIN("menu.main"),
    MENU_MAIN_LIST("menu.main_list"),
    MENU_MAIN_LIST_LORE("menu.main_list_lore"),
    MENU_MAIN_CREATE("menu.main_create"),
    MENU_MAIN_CREATE_LORE("menu.main_create_lore"),
    MENU_MAIN_NPC("menu.main_npc"),
    MENU_MAIN_NPC_LORE("menu.main_npc_lore"),

    MENU_NPC_PRESET("menu.npc_preset"),
    MENU_NPC_PRESET_NAME("menu.npc_preset_name"),
    MENU_NPC_PRESET_INFO("menu.npc_preset_info"),
    MENU_NPC_PRESET_USE_LORE("menu.npc_preset_use_lore"),
    MENU_NPC_PRESET_DELETE_LORE("menu.npc_preset_delete_lore"),
    MENU_NPC_PRESET_CREATE("menu.npc_preset_create"),
    MENU_NPC_PRESET_CREATE_LORE("menu.npc_preset_create_lore"),
    MENU_NPC_PICK("menu.npc_pick"),
    MENU_NPC_PICK_LORE("menu.npc_pick_lore"),
    MENU_NPC_MANAGE_LORE("menu.npc_manage_lore"),
    MENU_NPC_CREATE_TYPE("menu.npc_create_type"),
    MENU_NPC_CREATE_PLAYER("menu.npc_create_player"),
    MENU_NPC_CREATE_PLAYER_LORE("menu.npc_create_player_lore"),
    MENU_NPC_CREATE_MM("menu.npc_create_mm"),
    MENU_NPC_CREATE_MM_LORE("menu.npc_create_mm_lore"),
    MENU_NPC_CREATE_ME("menu.npc_create_me"),
    MENU_NPC_CREATE_ME_LORE("menu.npc_create_me_lore"),
    MENU_SPAWN_TYPE_LIBRARY("menu.spawn_type_library"),
    MENU_SPAWN_TYPE_LIBRARY_LORE("menu.spawn_type_library_lore"),
    MENU_NPC_PRESET_EQUIP_LORE("menu.npc_preset_equip_lore"),
    MENU_NPC_EQUIP("menu.npc_equip"),
    MENU_NPC_EQUIP_SLOT_HEAD("menu.npc_equip_slot_head"),
    MENU_NPC_EQUIP_SLOT_CHEST("menu.npc_equip_slot_chest"),
    MENU_NPC_EQUIP_SLOT_LEGS("menu.npc_equip_slot_legs"),
    MENU_NPC_EQUIP_SLOT_FEET("menu.npc_equip_slot_feet"),
    MENU_NPC_EQUIP_SLOT_HAND("menu.npc_equip_slot_hand"),
    MENU_NPC_EQUIP_SLOT_OFF("menu.npc_equip_slot_off"),
    MENU_NPC_EQUIP_EMPTY("menu.npc_equip_empty"),
    MENU_NPC_EQUIP_FILLED("menu.npc_equip_filled"),
    MENU_NPC_EQUIP_FILLED_LORE("menu.npc_equip_filled_lore"),
    MSG_NPC_EQUIP_SET("msg.npc_equip_set"),
    MSG_NPC_EQUIP_CLEARED("msg.npc_equip_cleared"),
    MENU_NPC_EQUIP_HINT("menu.npc_equip_hint"),
    MENU_NPC_EQUIP_DONE("menu.npc_equip_done"),
    MENU_NPC_EQUIP_CLEAR("menu.npc_equip_clear"),
    MENU_NPC_EQUIP_COSMETICS("menu.npc_equip_cosmetics"),
    MENU_NPC_EQUIP_COSMETICS_LORE("menu.npc_equip_cosmetics_lore"),
    MENU_NPC_COSMETICS("menu.npc_cosmetics"),
    MENU_NPC_COSMETIC_EMPTY("menu.npc_cosmetic_empty"),
    MENU_NPC_COSMETIC_FILLED("menu.npc_cosmetic_filled"),
    MENU_NPC_COSMETIC_HINT("menu.npc_cosmetic_hint"),
    MENU_NPC_COSMETIC_PICK("menu.npc_cosmetic_pick"),
    MENU_NPC_COSMETIC_CLEAR("menu.npc_cosmetic_clear"),
    MENU_NPC_COSMETIC_NONE("menu.npc_cosmetic_none"),
    MSG_NPC_COSMETIC_SET("msg.npc_cosmetic_set"),
    MSG_NPC_COSMETIC_CLEARED("msg.npc_cosmetic_cleared"),
    MENU_ACTION_EQUIP("menu.action_equip"),
    MENU_ACTION_EQUIP_LORE("menu.action_equip_lore"),

    MENU_LIST("menu.list"),
    MENU_LIST_ID("menu.list_id"),
    MENU_LIST_EDIT_LORE("menu.list_edit_lore"),
    MENU_LIST_DELETE_LORE("menu.list_delete_lore"),
    MENU_LIST_PREV("menu.list_prev"),
    MENU_LIST_BACK("menu.list_back"),
    MENU_LIST_NEXT("menu.list_next"),

    MENU_STUDIO("menu.studio"),
    MENU_STUDIO_TIME("menu.studio_time"),
    MENU_STUDIO_CURRENT("menu.studio_current"),
    MENU_STUDIO_ADD_ACTION("menu.studio_add_action"),
    MENU_STUDIO_ADD_ACTION_LORE("menu.studio_add_action_lore"),
    MENU_STUDIO_ACTION_NAME("menu.studio_action_name"),
    MENU_STUDIO_ACTION_TARGET("menu.studio_action_target"),
    MENU_STUDIO_ADD_CAMERA("menu.studio_add_camera"),
    MENU_STUDIO_ADD_CAMERA_LORE("menu.studio_add_camera_lore"),
    MENU_STUDIO_CAMERA_NAME("menu.studio_camera_name"),
    MENU_STUDIO_ADD_EFFECT("menu.studio_add_effect"),
    MENU_STUDIO_ADD_EFFECT_LORE("menu.studio_add_effect_lore"),
    MENU_STUDIO_EFFECT_NAME("menu.studio_effect_name"),
    MENU_STUDIO_EFFECT_VALUE("menu.studio_effect_value"),
    MENU_STUDIO_DELETE_LORE("menu.studio_delete_lore"),
    MENU_STUDIO_PREV("menu.studio_prev"),
    MENU_STUDIO_BACK("menu.studio_back"),
    MENU_STUDIO_PLAY("menu.studio_play"),
    MENU_STUDIO_SAVE("menu.studio_save"),
    MENU_STUDIO_STOP("menu.studio_stop"),
    MENU_STUDIO_NEXT("menu.studio_next"),
    MENU_STUDIO_ENV_RECORD("menu.studio_env_record"),
    MENU_STUDIO_ENV_RECORD_LORE("menu.studio_env_record_lore"),
    MENU_STUDIO_NPC_LIBRARY("menu.studio_npc_library"),
    MENU_STUDIO_NPC_LIBRARY_LORE("menu.studio_npc_library_lore"),

    MENU_ACTION("menu.action"),
    MENU_ACTION_SPAWN("menu.action_spawn"),
    MENU_ACTION_SPAWN_LORE("menu.action_spawn_lore"),
    MENU_ACTION_MOVE("menu.action_move"),
    MENU_ACTION_MOVE_LORE("menu.action_move_lore"),
    MENU_ACTION_ANIMATION("menu.action_animation"),
    MENU_ACTION_ANIMATION_LORE("menu.action_animation_lore"),
    MENU_ACTION_HIDE("menu.action_hide"),
    MENU_ACTION_HIDE_LORE("menu.action_hide_lore"),
    MENU_ACTION_SHOW("menu.action_show"),
    MENU_ACTION_SHOW_LORE("menu.action_show_lore"),
    MENU_ACTION_BACK("menu.action_back"),

    MENU_SPAWN_TYPE("menu.spawn_type"),
    MENU_SPAWN_TYPE_NPC("menu.spawn_type_npc"),
    MENU_SPAWN_TYPE_MM("menu.spawn_type_mm"),
    MENU_SPAWN_TYPE_ME("menu.spawn_type_me"),

    MENU_NPC_TYPE("menu.npc_type"),
    MENU_NPC_TYPE_PLAYER("menu.npc_type_player"),
    MENU_NPC_TYPE_ZOMBIE("menu.npc_type_zombie"),
    MENU_NPC_TYPE_PIG("menu.npc_type_pig"),
    MENU_NPC_TYPE_SKELETON("menu.npc_type_skeleton"),
    MENU_NPC_TYPE_CUSTOM("menu.npc_type_custom"),
    MENU_NPC_TYPE_CUSTOM_LORE("menu.npc_type_custom_lore"),

    MENU_ANIMATION("menu.animation"),
    MENU_ANIMATION_SPIN("menu.animation_spin"),
    MENU_ANIMATION_SPIN_LORE("menu.animation_spin_lore"),
    MENU_ANIMATION_SPRINT("menu.animation_sprint"),
    MENU_ANIMATION_SPRINT_LORE("menu.animation_sprint_lore"),
    MENU_ANIMATION_SWIM("menu.animation_swim"),
    MENU_ANIMATION_SWIM_LORE("menu.animation_swim_lore"),
    MENU_ANIMATION_SNEAK("menu.animation_sneak"),
    MENU_ANIMATION_SNEAK_LORE("menu.animation_sneak_lore"),
    MENU_ANIMATION_SLEEP("menu.animation_sleep"),
    MENU_ANIMATION_SLEEP_LORE("menu.animation_sleep_lore"),
    MENU_ANIMATION_CUSTOM("menu.animation_custom"),
    MENU_ANIMATION_CUSTOM_LORE("menu.animation_custom_lore"),
    MENU_ANIMATION_REMAP("menu.animation_remap"),
    MENU_ANIMATION_REMAP_LORE("menu.animation_remap_lore"),
    MENU_ANIMATION_CHANGEPART("menu.animation_changepart"),
    MENU_ANIMATION_CHANGEPART_LORE("menu.animation_changepart_lore"),
    MENU_ANIMATION_GESTURE("menu.animation_gesture"),
    MENU_ANIMATION_GESTURE_LORE("menu.animation_gesture_lore"),
    MENU_ANIMATION_AM("menu.animation_am"),
    MENU_ANIMATION_AM_LORE("menu.animation_am_lore"),
    MENU_ANIMATION_STOP("menu.animation_stop"),
    MENU_ANIMATION_STOP_LORE("menu.animation_stop_lore"),

    MENU_TOGGLE_TITLE("menu.toggle.title"),
    MENU_TOGGLE_ON_NAME("menu.toggle.on_name"),
    MENU_TOGGLE_ON_LORE("menu.toggle.on_lore"),
    MENU_TOGGLE_OFF_NAME("menu.toggle.off_name"),
    MENU_TOGGLE_OFF_LORE("menu.toggle.off_lore"),

    MENU_NPC("menu.npc"),
    MENU_NPC_NAME("menu.npc_name"),
    MENU_NPC_SELECT_LORE("menu.npc_select_lore"),
    MENU_NPC_ID_LORE("menu.npc_id_lore"),
    MENU_NPC_BACK("menu.npc_back"),

    MENU_EFFECT("menu.effect"),
    MENU_EFFECT_SOUND("menu.effect_sound"),
    MENU_EFFECT_SOUND_LORE("menu.effect_sound_lore"),
    MENU_EFFECT_PARTICLE("menu.effect_particle"),
    MENU_EFFECT_PARTICLE_LORE("menu.effect_particle_lore"),
    MENU_EFFECT_TITLE("menu.effect_title"),
    MENU_EFFECT_TITLE_LORE("menu.effect_title_lore"),
    MENU_EFFECT_MESSAGE("menu.effect_message"),
    MENU_EFFECT_MESSAGE_LORE("menu.effect_message_lore"),
    MENU_EFFECT_COMMAND("menu.effect_command"),
    MENU_EFFECT_COMMAND_LORE("menu.effect_command_lore"),
    MENU_EFFECT_LIGHTNING("menu.effect_lightning"),
    MENU_EFFECT_LIGHTNING_LORE("menu.effect_lightning_lore"),
    MENU_EFFECT_DIALOGUE("menu.effect_dialogue"),
    MENU_EFFECT_DIALOGUE_LORE("menu.effect_dialogue_lore"),
    MENU_EFFECT_DIALOGUE_TITLE("menu.effect_dialogue_title"),
    MENU_EFFECT_DIALOGUE_TITLE_LORE("menu.effect_dialogue_title_lore"),
    MENU_EFFECT_DIALOGUE_ACTIONBAR("menu.effect_dialogue_actionbar"),
    MENU_EFFECT_DIALOGUE_ACTIONBAR_LORE("menu.effect_dialogue_actionbar_lore"),
    MENU_EFFECT_WAIT("menu.effect_wait"),
    MENU_EFFECT_WAIT_LORE("menu.effect_wait_lore"),
    MENU_EFFECT_ENV_RECORD("menu.effect_env_record"),
    MENU_EFFECT_ENV_RECORD_LORE("menu.effect_env_record_lore"),
    MENU_EFFECT_BACK("menu.effect_back"),

    // 메시지 관련
    MSG_INPUT_NAME("msg.input_name"),
    MSG_INPUT_SPAWN("msg.input_spawn"),
    MSG_INPUT_SPAWN_MM("msg.input_spawn_mm"),
    MSG_INPUT_SPAWN_ME("msg.input_spawn_me"),
    MSG_INPUT_SPAWN_NPC_PLAYER("msg.input_spawn_npc_player"),
    MSG_INPUT_SPAWN_NPC_MOB("msg.input_spawn_npc_mob"),
    MSG_INPUT_CUSTOM_TYPE("msg.input_custom_type"),
    MSG_INPUT_CUSTOM_TYPE_CONFIRM("msg.input_custom_type_confirm"),
    MSG_ERROR_INVALID_TYPE("msg.error_invalid_type"),
    MSG_INPUT_SOUND("msg.input_sound"),
    MSG_INPUT_PARTICLE("msg.input_particle"),
    MSG_INPUT_TITLE("msg.input_title"),
    MSG_INPUT_MESSAGE("msg.input_message"),
    MSG_INPUT_DIALOGUE("msg.input_dialogue"),
    MSG_INPUT_WAIT("msg.input_wait"),
    MSG_INPUT_COMMAND("msg.input_command"),
    MSG_INPUT_ANIMATION("msg.input_animation"),
    MSG_INPUT_GESTURE("msg.input_gesture"),
    MSG_INPUT_AM("msg.input_am"),
    MSG_INPUT_REMAP("msg.input_remap"),
    MSG_INPUT_CHANGEPART("msg.input_changepart"),
    MSG_INPUT_ANIM_STOP("msg.input_anim_stop"),
    MSG_CREATE_SUCCESS("msg.create_success"),
    MSG_SAVE_SUCCESS("msg.save_success"),
    MSG_DELETE_ADMIN("msg.delete_admin"),
    MSG_CAMERA_STATIC_SET("msg.camera_static_set"),
    MSG_RECORD_START("msg.record_start"),
    MSG_RECORD_END("msg.record_end"),
    MSG_LIGHTNING_ADDED("msg.lightning_added"),
    MSG_DIALOGUE_ADDED("msg.dialogue_added"),
    MSG_WAIT_ADDED("msg.wait_added"),

    MSG_ENV_RECORD_START("msg.env_record_start"),
    MSG_ENV_RECORD_END("msg.env_record_end"),
    MSG_NPC_PRESET_SAVED("msg.npc_preset_saved"),
    MSG_NPC_PRESET_INSERTED("msg.npc_preset_inserted"),
    MSG_NPC_PRESET_SELECTED("msg.npc_preset_selected"),
    MSG_INPUT_NPC_PRESET("msg.input_npc_preset"),
    MSG_INPUT_NPC_CREATE_PLAYER("msg.input_npc_create_player"),
    MSG_INPUT_NPC_CREATE_MM("msg.input_npc_create_mm"),
    MSG_INPUT_NPC_CREATE_ME("msg.input_npc_create_me"),
    MSG_INPUT_NPC_EDIT_VANILLA("msg.input_npc_edit_vanilla"),
    MSG_INPUT_NPC_EDIT_MM("msg.input_npc_edit_mm"),
    MSG_INPUT_NPC_EDIT_ME("msg.input_npc_edit_me"),
    MSG_NPC_LIBRARY_EMPTY("msg.npc_library_empty"),
    MSG_NPC_EQUIP_SAVED("msg.npc_equip_saved"),
    MSG_NPC_EQUIP_ADDED("msg.npc_equip_added"),

    BTN_CAMERA_STATIC("btn.camera_static"),
    BTN_CAMERA_RECORD("btn.camera_record"),

    MSG_PAUSE_TITLE("msg.pause_title"),
    MSG_PAUSE_SUBTITLE("msg.pause_subtitle"),
    MSG_PAUSE_RESUME("msg.pause_resume"),
    MSG_PAUSE_SKIP("msg.pause_skip"),
    MSG_DIALOGUE_HINT_NEXT("msg.dialogue_hint_next"),
    MSG_DIALOGUE_HINT_CONTINUE("msg.dialogue_hint_continue");

    private final String path;

    LangKey(String path) {
        this.path = path;
    }

    public String getPath() {
        return path;
    }
}